hizride_backend/config/routes.rb
Rails.application.routes.draw do
  resources :routes
  resources :current_locations
  resources :users

  resource :session, only: [:new, :create, :destroy]

  get 'drivermap', to:'users#drivermap'
end

hizride_backend/app/models/current_location.rb
class CurrentLocation < ActiveRecord::Base
  belongs_to :user

  def close_to_location(lat, lng)
    if ((self.lat.to_i - lat.to_i).abs < 0.001) && ((self.lng.to_i - lng.to_i).abs < 0.001)
      return true
    else
      return false
    end
  end
end

hizride_backend/app/controllers/current_locations_controller.rb
class CurrentLocationsController < ApplicationController
  before_action :set_current_location, only: [:show, :edit, :update, :destroy]

  # GET /current_locations
  # GET /current_locations.json
  def index
    @current_locations = CurrentLocation.all
  end

  # GET /current_locations/1
  # GET /current_locations/1.json
  def show
  end

  # GET /current_locations/new
  def new
    @current_location = CurrentLocation.new
  end

  # GET /current_locations/1/edit
  def edit
  end

  # POST /current_locations
  # POST /current_locations.json
  def create
    @current_location = CurrentLocation.new(current_location_params)

    respond_to do |format|
      if @current_location.save
        format.html { redirect_to @current_location, notice: 'Current location was successfully created.' }
        format.json { render :show, status: :created, location: @current_location }
      else
        format.html { render :new }
        format.json { render json: @current_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /current_locations/1
  # PATCH/PUT /current_locations/1.json
  def update
    respond_to do |format|
      if @current_location.update(current_location_params)
        format.html { redirect_to @current_location, notice: 'Current location was successfully updated.' }
        format.json { render :show, status: :ok, location: @current_location }
      else
        format.html { render :edit }
        format.json { render json: @current_location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /current_locations/1
  # DELETE /current_locations/1.json
  def destroy
    @current_location.destroy
    respond_to do |format|
      format.html { redirect_to current_locations_url, notice: 'Current location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_current_location
      @current_location = CurrentLocation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def current_location_params
      params.require(:current_location).permit(:lat, :lng, :user_id)
    end
end

hizride_backend/app/helpers/current_locations_helper.rb
module CurrentLocationsHelper
end

hizride_backend/app/views/current_locations/_form.html.erb
<%= form_for(@current_location) do |f| %>
  <% if @current_location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@current_location.errors.count, "error") %> prohibited this current_location from being saved:</h2>

      <ul>
      <% @current_location.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hizride_backend/app/views/current_locations/edit.html.erb
<h1>Editing Current Location</h1>

<%= render 'form' %>

<%= link_to 'Show', @current_location %> |
<%= link_to 'Back', current_locations_path %>

hizride_backend/app/views/current_locations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Current Locations</h1>

<table>
  <thead>
    <tr>
      <th>Lat</th>
      <th>Lng</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @current_locations.each do |current_location| %>
      <tr>
        <td><%= current_location.lat %></td>
        <td><%= current_location.lng %></td>
        <td><%= current_location.user_id %></td>
        <td><%= link_to 'Show', current_location %></td>
        <td><%= link_to 'Edit', edit_current_location_path(current_location) %></td>
        <td><%= link_to 'Destroy', current_location, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Current location', new_current_location_path %>

hizride_backend/app/views/current_locations/new.html.erb
<h1>New Current Location</h1>

<%= render 'form' %>

<%= link_to 'Back', current_locations_path %>

hizride_backend/app/views/current_locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lat:</strong>
  <%= @current_location.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @current_location.lng %>
</p>

<p>
  <strong>User:</strong>
  <%= @current_location.user_id %>
</p>

<%= link_to 'Edit', edit_current_location_path(@current_location) %> |
<%= link_to 'Back', current_locations_path %>